language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.4'
  - 'hhvm'
  - 'nightly'

sudo: false

git:
  submodules: false

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm

before_script:
  - make install

script:
  - make check
  - make test
