version: 2

jobs:
  build:
    machine:
      php:
    working_directory: ~/weather-module
    environment:
    steps:
      pre: 
        - "make install"
        - "make check"
      override:
        - "make test"