version: 2
jobs:
  build:
    working_directory: ~/weather_module
    docker:
      - image: php:7.1-apache
    steps:
      - run:
          name: Setup
          command: make install
      - run:
          name: Check
          command: make check
      - run:
          name: test
          command: make test