version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers

    working_directory: ~

    steps:
      pre:
        - run: make install
        - run: make check
    
      override:
        - run: make test